### ISSUE TITLE
Reject TCPIP Traffic

### ISSUE THREAD

**Issue by georgesmart1** [asdil12/pymultimonaprs#15]
Hello.

I have noticed a small issue. Someone in radio range of me is sending IGATE->RF, and pymultimonaprs subsuiquently re-pushes these packets back to TCPIP.

Is there a way to reject packets with "TCPIP", "NOGATE", or "RFONLY" in the path?

George M1GEO

**Comment by asdil12** [comment]
I created a patch but it is not tested, yet.
Could you give it a try?

**Comment by georgesmart1** [comment]
Sure. 
Just a guy local to me feels the need to spew tcpip crap out.
If you explain to me how to get the patch I'll gladly try it. 
Thanks. 
George M1GEO.
GB7KH repeater keeper
GB0SNB RX iGate
-- 
George Smart, M1GEO.
http://www.george-smart.co.uk
Mobile: +44 (0)771 963 1311
Skype: george-smart
On 15 May 2015 09:36, Dominik Heidler <notifications@github.com> wrote:I created a patch but it is not tested, yet.
Could you give it a try?

**Comment by asdil12** [comment]
https://github.com/asdil12/pymultimonaprs/commit/9aa9dec5ad76bf8a63c7c14fd6641b00f4683e4f.patch

**Comment by georgesmart1** [comment]
I applied the patch:
  git apply -v 9aa9dec5ad76bf8a63c7c14fd6641b00f4683e4f.patch
  Checking patch bin/pymultimonaprs...
  Applied patch bin/pymultimonaprs cleanly.

Then re-installed it:
  python2 setup.py install

Then, when I run the thing, I notice that I still get errors with the APRS-IS network. Maybe I didn't understand the update/patching?

The error I get is: 
  Receive drops: 0 dupes, 6 errors in 9
  3rd-party packet gated TCPIP>RF>TCPIP: 6

Thanks again.
G M1GEO.

**Comment by asdil12** [comment]
Could you run pymultimonaprs in debug mode (commandline option -v) and have a 
look at the logfile.

**Comment by georgesmart1** [comment]
Log file here: http://m1geo.com/temp/pymultimonaprs4.log
Doesn't appear to be rejecting things with TCPIP in the path.

**Comment by asdil12** [comment]
```
[2015-05-22 01:46:30]    DEBUG: sending: MB7UEK>APBPQ1,MB7UH*,WIDE3-1,qAR,GB0SNB:}GB7KH-S>APJIO4,TCPIP,MB7UEK*:;GB7KH  B *220128z5140.34ND00015.44EaRNG0050 440 Voice 439.6125 -9 MHz
```


OK, I need some confirmation:
- Is the MB7UEK the iGATE -> RF repeater?
- Is GB7KH-S the src callsign of the retransmitted pkg?

**Comment by asdil12** [comment]
APRS Specs: ftp://ftp.tapr.org/aprssig/aprsspec/spec/aprs101/APRS101.pdf (page 95):
> After a packet emerges from a third-party network, the receiving gateway
> station modifies it (by inserting a **}** Third-Party Data Type Identifier and
> modifying the Source Path Header) before transmitting it on the local APRS
> network.

I'm not sure if I can simply reject all pkgs with third party data type.

**Comment by asdil12** [comment]
The current code does not match the TCPIP in the path because it is actually not part of the path but part of the payload (encapsulated).

**Comment by georgesmart1** [comment]
The APRSIS servers report this as a fault. If, for example, you look at http://london.aprs2.net:14501/ you'll find my node in question, GB0SNB. The packet count is in red, and clicking it shows that it doesn't like TCP>RF>TCP as it shows it. 
In my log, MB7UUE is throwing TCP data onto RF. Much to the annoyance of everyone here. 
George. M1GEO.

**Comment by asdil12** [comment]
Please give this patch a try:

https://github.com/asdil12/pymultimonaprs/commit/e1bc00aba3ff4fef84b4c70da9653cd6bfcd022f.patch

**Comment by georgesmart1** [comment]
That latest patch seems to have got it: 
[2015-05-29 17:18:58]    DEBUG: rejected: MB7UEK>APBPQ1,MB7UH*,WIDE3-2,qAR,GB0SNB:}G0HWC>APWW10,TCPIP,MB7UEK*:;G0HWC-WX *291820z5148.82N/00110.13E_275/008g014t056r000p007P007h67b10054

Thanks so much for taking the time to look into this for me... I will run it for a while at GB0SNB, and then maybe roll it into the main branch?

Thanks M1GEO.com
