### ISSUE TITLE
Multiple gateway servers?

### ISSUE THREAD

**Issue by mmiller7** [asdil12/pymultimonaprs#18]
Is it possible to specify multiple gateway servers?

I'd like to specify a particular IP for which server to connect to.  The issue I am having, depending when I start pymultimonaprs it will connect to one of the servers at random but the latency varies from 10ms to 150ms depending which server it picks.

I'd like to be able to specify "try and connect to IP-A, IP-B, noam.aprs2.net," so it so that it will still fall back to a working server if the first ones fail, but will attempt to use a particular server first.

**Comment by mach327** [comment]
I could send you a patch if this is still something that interests you, but why does a difference of 140ms matter?

**Comment by mmiller7** [comment]
As I understand it, aprs.fi will only the path of the first machine to report a station, I have been trying to test my setup before deploying it but I'm only seeing a couple packets that show they were reported thru my iGate on the map, the majority of all packets show up that they are bouncing thru multiple digipeaters and thru a far-away iGate before mine reports.

I'm at a loss of what else to try, I see lots received when I run with a -v flag but the only time I see any number consistently relay is if I connected to an aprs-server with very low ping latency (there are many in the pool when you run nslookup).

If you have any alternative suggestions, I would love to hear them.

**Comment by mach327** [comment]
Ah, that makes sense. We'll see how my first pull request goes!
