### ISSUE TITLE
Negative value in PPM results in wrong command line

### ISSUE THREAD

**Issue by mkubon** [asdil12/pymultimonaprs#19]
Hi,

Frank (DG3KCE) found an error, if he want to enter a negative value for the PPM. I think that is because of the space between the -p and the value.

Example (-29): rtl_fm -f 144800000 -f 145825000 -s 22050 -p -29 -g 0 -l 10 - -E none -d

It will start 2 decodings instead of one and the PPM will result in a separate option.
Can you please change the source, where the space after ther -p option is removed?

Best regards, Marco

**Comment by asdil12** [comment]
Please give this patch a try: https://github.com/asdil12/pymultimonaprs/commit/449278c8f926df817cd5255c6e1793860b6ea5b2.patch

**Comment by mkubon** [comment]
Works for me after patching and building:

29980 pts/0    Sl     0:01 rtl_fm -f 144800000 -s 22050 -p-17 -g 42 -E offset -d 0 -
29981 pts/0    S      0:00 multimon-ng -a AFSK1200 -A -t raw -

Can be released. Thank you.
