### ISSUE TITLE
Filter command sent to the APRS-IS server

### ISSUE THREAD

**Issue by corey-eng** [asdil12/pymultimonaprs#25]
Not sure how much this matters but the filter command sent to the APRS-IS is hard coded in the gate.py file and should probably be more generic or user defined.

Existing (Line 60):

self.log.info("login %s (PyMultimonAPRS %s)" % (self.callsign, version))
self.socket.send("user %s pass %s vers PyMultimonAPRS %s filter **r/38/-171/1**\r\n" %
						(self.callsign, self.passcode, version))

Modified Example (Line 60): "Changed **r/38/-171/1** to **m/80**"

self.log.info("login %s (PyMultimonAPRS %s)" % (self.callsign, version))
self.socket.send("user %s pass %s vers PyMultimonAPRS %s filter **m/80**\r\n" %
						(self.callsign, self.passcode, version))

Reference:
http://www.aprs-is.net/javAPRSFilter.aspx

**Comment by asdil12** [comment]
The filter command is hardcoded to a position that is nearly impossible
to produce any output data. I don't need to receive any data - what
should I do with it - I can't send it. So I minimize the rx traffic.

**Comment by corey-eng** [comment]
Thanks for the reply and the information. It does make sense, it just looks strange when you see it on the APRS-IS server web page.

Corey


-------- Original Message --------
