### ISSUE TITLE
Please document pymultimonaprs.json

### ISSUE THREAD

**Issue by oh7fxk** [asdil12/pymultimonaprs#30]
Simple things, like how to turn offsettuning on etc. 
Would help all of us!

But thank You for great software!

**Comment by oh7fxk** [comment]
It seems to be possible use offset tuning only with e4000 tuner? Not with r820t?

**Comment by asdil12** [comment]
To enable offset tuning you have to set `offset_tuning` to `true` in the config file.
See https://github.com/asdil12/pymultimonaprs/blob/master/pymultimonaprs.json

I don't know, which tuner will work.
I only redirect that option by adding `-E offset` to the `rtl_fm` command that I call internally to receive the radio signal.
